image:
  file: .gitpod.Dockerfile

tasks:
  - init: >
      yarn install --frozen-lockfile &&
      yarn run build && 
      yarn run prisma:migrate
    command: yarn run dev

ports:
  - port: 3000
    onOpen: open-preview
