name: Test

on: push

jobs:
  build-node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Check TypeScript types
        run: yarn typecheck

  build-heroku:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check compatibility with Heroku
        run: >
          docker run 
          --volume $(pwd):/tmp/app
          gliderlabs/herokuish
          /bin/herokuish test
